# produces a docker image suitable to build pmacct

FROM ubuntu:jammy

ARG DEBIAN_FRONTEND=noninteractive
ARG DISTRIBUTION=ubuntu:jammy
ARG GIT_HASH
ARG GIT_URL

RUN apt-get update && \
    apt-get install -y \
    autoconf \
    automake \
    bash \
    bison \
    cmake \
    build-essential \
    default-libmysqlclient-dev \
    libnuma-dev \
    flex \
    gcc \
    git \
    libcurl4-openssl-dev \
    libjansson-dev \
    libjson-c-dev \
    libnetfilter-log-dev \
    libpcap-dev \
    libpq-dev \
    libsnappy-dev \
    libsqlite3-dev \
    libssl-dev \
    libgnutls28-dev \
    libtool \
    make \
    pkg-config \
    sudo \
    wget \
    zlib1g-dev \
    curl \
    clang

COPY ./ci/deps.sh .
RUN ./deps.sh

COPY ./ci/install_pmacct_gauze.sh .
RUN ./install_pmacct_gauze.sh $GIT_URL $GIT_HASH

ENTRYPOINT ["/bin/bash"]
