# produces a docker image suitable to build pmacct

FROM rockylinux:9

ARG DISTRIBUTION=rockylinux:9
ARG GIT_HASH
ARG GIT_URL

RUN yum install -y dnf-plugins-core && \
    yum config-manager --set-enabled crb && \
    yum install -y \
    autoconf \
    automake \
    bash \
    bison \
    cmake \
    epel-release \
    flex \
    gcc \
    gcc-c++ \
    git \
    glibc-devel \
    glibc-headers \
    jansson-devel \
    json-c-devel \
    libcurl-devel \
    libpcap-devel \
    libpq-devel \
    libstdc++-devel \
    libtool \
    make \
    mysql-devel \
    numactl-devel \
    openssl-devel \
    pkgconfig \
    snappy-devel \
    sqlite-devel \
    gnutls-devel \
    sudo \
    wget \
    which \
    zlib-devel \
    clang

COPY ./ci/deps.sh .
RUN ./deps.sh

COPY ./ci/install_pmacct_gauze.sh .
RUN ./install_pmacct_gauze.sh $GIT_URL $GIT_HASH

ENTRYPOINT ["/bin/bash"]
